### ISSUE TITLE
More single channel video inquiry

### ISSUE THREAD

**Issue by dialuser** [sihyun-yu/PVDM#12] opened 2023-03-25 14:33 UTC
Hi I'm using single channel 128x128 video. The ae_loss calculation threw an error. I think somewhere in the loss function it expects 3-channel frames. Can you provide some advice on dealing with single channel videos? Because you listed in/out channels as parameters, I think you probably have tested with single-channel before, no?

```
File "/home/work/PVDM/tools/trainer.py", line 188, in first_stage_train
    ae_loss = criterion(vq_loss, x,
  File "/home/anaconda3/envs/mympi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/PVDM/losses/perceptual.py", line 118, in forward
    logits_real_2d, pred_real_2d = self.discriminator_2d(inputs_2d)
  File "/home/anaconda3/envs/mympi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/PVDM/losses/perceptual.py", line 207, in forward
    res.append(model(res[-1]))
  File "/home/anaconda3/envs/mympi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/mympi/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/anaconda3/envs/mympi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/mympi/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/anaconda3/envs/mympi/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 4, 4], expected input[2, 1, 128, 128] to have 3 channels, but got 1 channels instead 
```

**Comment by dialuser** [comment] 2023-03-25 15:53
Ok, in first_stage.py, the input channel size needs to be specified to accomodate single channel

    criterion = LPIPSWithDiscriminator(disc_start   = args.lossconfig.params.disc_start,
                                       timesteps    = args.ddconfig.timesteps,
                                       disc_in_channels=args.ddconfig.in_channels #<----
                                       ).to(device)

**Comment by sihyun-yu** [comment] 2023-03-25 16:22
Hi,

it seems the issue is resolved. Will close the issue.

**Closed as completed by sihyun-yu** 2023-03-25 16:22 UTC
